global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  # Backend API metrics (if your Go app exposes /metrics endpoint)
  - job_name: 'clustersight-backend'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8081']

  # Additional Docker metrics from cAdvisor
  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
